import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import plugin from '../src/index.js';

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'clawsmith-'));
const handlers = new Map();
const commands = new Map();
const routes = [];
const api = { id: 'clawsmith', name: 'clawsmith', version: '0.2.0', pluginConfig: { outputDir: '.clawsmith', persistPromptBodies: true, persistMessageBodies: true, contextWindows: { 'openai/gpt-5.2-thinking': 200000 } }, runtime: { workspaceDir: tmp }, resolvePath: (p) => p, registerCommand(def) { commands.set(def.name, def); }, registerHttpRoute(def) { routes.push(def); }, on(name, fn) { handlers.set(name, fn); }, logger: { info() {}, warn() {}, error() {} } };
plugin.register(api);
const agentCtx = { agentId: 'main', sessionId: 'session-1', sessionKey: 'agent:main:test', runId: 'run-1', channelId: 'telegram', trigger: 'user' };
await handlers.get('session_start')?.({ sessionId: 'session-1', sessionKey: 'agent:main:test' }, { sessionId: 'session-1', sessionKey: 'agent:main:test' });
await handlers.get('llm_input')?.({ runId: 'run-1', sessionId: 'session-1', provider: 'openai', model: 'gpt-5.2-thinking', systemPrompt: 'system', prompt: 'hello', historyMessages: [{ role: 'user', content: 'hello' }], imagesCount: 0 }, agentCtx);
await handlers.get('before_tool_call')?.({ toolName: 'web_search', params: { q: 'openclaw' }, toolCallId: 'tool-1' }, { ...agentCtx, toolName: 'web_search', toolCallId: 'tool-1' });
await handlers.get('after_tool_call')?.({ toolName: 'web_search', params: { q: 'openclaw' }, toolCallId: 'tool-1', result: { ok: true }, durationMs: 42 }, { ...agentCtx, toolName: 'web_search', toolCallId: 'tool-1' });
await handlers.get('llm_output')?.({ runId: 'run-1', sessionId: 'session-1', provider: 'openai', model: 'gpt-5.2-thinking', assistantTexts: ['done'], lastAssistant: { role: 'assistant', content: 'done' }, usage: { input: 1500, output: 180, cacheRead: 200, cacheWrite: 0, total: 1880 } }, agentCtx);
await handlers.get('agent_end')?.({ messages: [], success: true, durationMs: 321 }, agentCtx);
await handlers.get('session_end')?.({ sessionId: 'session-1', messageCount: 3, durationMs: 400 }, { sessionId: 'session-1', sessionKey: 'agent:main:test' });
const probe = commands.get('probe');
const probeOut = await probe.handler({ args: 'status' });
const traceFile = path.join(tmp, '.clawsmith', 'traces', 'run-1.json');
const trace = JSON.parse(fs.readFileSync(traceFile, 'utf8'));
console.log(JSON.stringify({ ok: true, workspace: tmp, registeredHooks: Array.from(handlers.keys()), registeredCommand: commands.has('probe'), registeredRoutes: routes.map(r => r.path), latestProbeOutput: probeOut.text, traceSummary: { traceId: trace.traceId, sessionId: trace.sessionId, provider: trace.provider, model: trace.model, usage: trace.usage, contextRatio: trace.contextRatio, toolCount: trace.toolSpans.length, success: trace.success } }, null, 2));
