import { MessageEntry, CompactEvent, getCompactedMessages, JournalEntry } from "../core/jsonl-parser.ts";
export interface ImportanceLoss { message: MessageEntry; score: number; reasons: string[]; }
export type SummaryQuality = "good" | "partial" | "poor";
export interface CompactAnalysis { event: CompactEvent; compactedMessages: MessageEntry[]; importantLosses: ImportanceLoss[]; summaryQuality: SummaryQuality; }
const PREFERENCE_PATTERNS = [/\b(use|prefer|always|never|don'?t|avoid|must|should|require|need)\b/i,/\bnot\s+(use|do|allow|want)\b/i,/\binstead\s+of\b/i];
const TECHNICAL_PATTERNS = [/[./\\][a-zA-Z0-9_-]+\.[a-zA-Z]{1,10}/,/\b[A-Z_]{2,}\b/,/`[^`]+`/,/```[\s\S]+?```/,/\b(port|host|url|api|key|token|secret|password|config|env)\b/i,/https?:\/\//];
const ENTITY_PATTERNS = [/\b[A-Z][a-z]+(?:[A-Z][a-z]+)+\b/,/\b(project|repo|database|service|component|module|package)\s+\w+/i];
const DECISION_PATTERNS = [/\b(decided|agreed|confirmed|settled on|going with|chose|selected)\b/i,/\b(the plan is|we will|I will|let's)\b/i];
export function scoreLoss(message: MessageEntry, summaryText: string): { score: number; reasons: string[] } { if ((message as any).role !== "user" && (message as any).role !== "assistant") return { score: 0, reasons: [] }; const content = (message as any).content; const lowerSummary = summaryText.toLowerCase(); const reasons: string[] = []; let score = 0; for (const pattern of PREFERENCE_PATTERNS) { const match = pattern.exec(content); if (match) { const phrase = extractPhrase(content, match.index, 40); if (phrase && !lowerSummary.includes(phrase.toLowerCase().slice(0, 20))) { score += 0.3; reasons.push("Preference or constraint statement"); break; } } } for (const pattern of TECHNICAL_PATTERNS) { const match = pattern.exec(content); if (match) { const val = match[0].slice(0, 30); if (!lowerSummary.includes(val.toLowerCase())) { score += 0.25; reasons.push("Technical detail (code, path, config)"); break; } } } for (const pattern of ENTITY_PATTERNS) { const match = pattern.exec(content); if (match) { const val = match[0].toLowerCase(); if (!lowerSummary.includes(val)) { score += 0.2; reasons.push("Named entity or project reference"); break; } } } for (const pattern of DECISION_PATTERNS) { if (pattern.test(content)) { score += 0.25; reasons.push("Decision or agreement statement"); break; } } if ((message as any).role === "user" && score > 0) score = Math.min(score * 1.2, 1); if (score === 0 && content.toLowerCase().length > 200) { score = 0.05; reasons.push("Long message (may contain context)"); } return { score: Math.min(score, 1), reasons }; }
export function analyzeCompaction(event: CompactEvent, allEntries: JournalEntry[], previousFirstKeptId?: string): CompactAnalysis { const compactedMessages = getCompactedMessages(allEntries, event, previousFirstKeptId); const losses: ImportanceLoss[] = []; for (const msg of compactedMessages) { const { score, reasons } = scoreLoss(msg, event.summaryText); if (score >= 0.2) losses.push({ message: msg, score, reasons }); } losses.sort((a,b)=>b.score-a.score); const quality = determineQuality(losses, compactedMessages.length); return { event, compactedMessages, importantLosses: losses, summaryQuality: quality }; }
function determineQuality(losses: ImportanceLoss[], totalMessages: number): SummaryQuality { const criticalLosses = losses.filter((l)=>l.score>=0.5).length; const moderateLosses = losses.filter((l)=>l.score>=0.2).length; if (criticalLosses >= 2 || (totalMessages > 5 && criticalLosses >= 1)) return "poor"; if (moderateLosses >= 2) return "partial"; return "good"; }
function extractPhrase(text: string, index: number, maxLen: number): string { const start = Math.max(0, index - 10); const end = Math.min(text.length, index + maxLen); return text.slice(start, end).replace(/\s+/g, " ").trim(); }
